version: "3"
services:
  alpine:
    build:
      context: .
    volumes:
      - ./data:/data
    entrypoint: bash
    command:
      - -c
      - |
        rm -f /data/packages.csv
        for package in $$(apk info -q); do
          apk info -q -s $$package | xargs | sed -e 's/ /, /g' >> /data/packages.csv
        done
